/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTpassword = new javax.swing.JTextField();
        jTusername = new javax.swing.JTextField();
        jLlogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(822, 756));
        setMinimumSize(new java.awt.Dimension(822, 756));
        setPreferredSize(new java.awt.Dimension(822, 756));
        getContentPane().setLayout(null);

        jTpassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTpassword);
        jTpassword.setBounds(170, 470, 410, 30);

        jTusername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTusernameActionPerformed(evt);
            }
        });
        getContentPane().add(jTusername);
        jTusername.setBounds(170, 370, 410, 30);

        jLlogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLloginMouseClicked(evt);
            }
        });
        getContentPane().add(jLlogin);
        jLlogin.setBounds(290, 530, 220, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/hal login.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 700);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTusernameActionPerformed

    private void jLloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLloginMouseClicked
        // TODO add your handling code here:
        try{
            Statement statement=(Statement) koneksi.GetConnection().createStatement();
            ResultSet result=statement.executeQuery("select*from admin where "+"username='"+jTusername.getText()+"'");
            if(result.next()){
                if(jTpassword.getText().equals(result.getString("password"))){
                    new home().show();
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(rootPane,"password salah");
                    jTpassword.setText("");
                    jTusername.requestFocus();
                }
            }else{
                JOptionPane.showMessageDialog(rootPane,"Username tidak ditemukan");
                jTusername.setText("");
                jTpassword.setText("");
                jTusername.requestFocus();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "gagal");
        }
    }//GEN-LAST:event_jLloginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLlogin;
    private javax.swing.JTextField jTpassword;
    private javax.swing.JTextField jTusername;
    // End of variables declaration//GEN-END:variables
}
