/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class tambahAnggota extends javax.swing.JFrame {

    /**
     * Creates new form tambahAnggota
     */
    public tambahAnggota() {
        initComponents();
        thisdate();
        random();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupJK = new javax.swing.ButtonGroup();
        jLsimpan2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTtanggalTerdaftar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTidAnggota = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTnamaLengkap = new javax.swing.JTextField();
        jTemail = new javax.swing.JTextField();
        rdPerempuan = new javax.swing.JRadioButton();
        rdLaki = new javax.swing.JRadioButton();
        jLclose = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(622, 456));
        setMinimumSize(new java.awt.Dimension(622, 456));
        setPreferredSize(new java.awt.Dimension(622, 456));
        getContentPane().setLayout(null);

        jLsimpan2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logo simpan_tambah.png"))); // NOI18N
        jLsimpan2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLsimpan2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLsimpan2MouseClicked(evt);
            }
        });
        getContentPane().add(jLsimpan2);
        jLsimpan2.setBounds(390, 320, 170, 50);

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(136, 96, 84));
        jLabel5.setText("Tanggal Terdaftar (YYYY-MM-DD)");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 270, 420, 24);
        getContentPane().add(jTtanggalTerdaftar);
        jTtanggalTerdaftar.setBounds(50, 300, 220, 30);

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(136, 96, 84));
        jLabel2.setText("Nama Lengkap");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 190, 190, 24);

        jTidAnggota.setBackground(new java.awt.Color(195, 158, 116));
        getContentPane().add(jTidAnggota);
        jTidAnggota.setBounds(50, 140, 220, 30);

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(136, 96, 84));
        jLabel3.setText("Jenis Kelamin");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(330, 190, 190, 29);

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(136, 96, 84));
        jLabel6.setText("ID Anggota");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 110, 160, 24);

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(136, 96, 84));
        jLabel7.setText("Email");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(330, 110, 160, 24);
        getContentPane().add(jTnamaLengkap);
        jTnamaLengkap.setBounds(50, 220, 220, 30);
        getContentPane().add(jTemail);
        jTemail.setBounds(330, 140, 220, 30);

        buttonGroupJK.add(rdPerempuan);
        rdPerempuan.setFont(new java.awt.Font("Leelawadee UI", 1, 20)); // NOI18N
        rdPerempuan.setForeground(new java.awt.Color(136, 96, 84));
        rdPerempuan.setText("P");
        getContentPane().add(rdPerempuan);
        rdPerempuan.setBounds(330, 220, 50, 35);

        buttonGroupJK.add(rdLaki);
        rdLaki.setFont(new java.awt.Font("Leelawadee UI", 1, 20)); // NOI18N
        rdLaki.setForeground(new java.awt.Color(136, 96, 84));
        rdLaki.setText("L");
        rdLaki.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(rdLaki);
        rdLaki.setBounds(420, 220, 50, 35);

        jLclose.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLclose.setForeground(new java.awt.Color(255, 0, 51));
        jLclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/x.png"))); // NOI18N
        jLclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLcloseMouseClicked(evt);
            }
        });
        getContentPane().add(jLclose);
        jLclose.setBounds(550, 10, 40, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/hal tambah anggota.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLsimpan2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLsimpan2MouseClicked
        // TODO add your handling code here:
        String getIdAnggota, getNama, getEmail, jenkel, getTanggal;
        getIdAnggota = jTidAnggota.getText();
        getNama = jTnamaLengkap.getText();
        getEmail = jTemail.getText();
        getTanggal = jTtanggalTerdaftar.getText();
        StringBuffer jk = new StringBuffer();
        if(rdPerempuan.isSelected()){
            jk.append(rdPerempuan.getText());
        }else if(rdLaki.isSelected()){
            jk.append(rdLaki.getText());
        }
        jenkel = jk.toString();
        
        if (empty(getIdAnggota) || empty(getNama) || empty(getEmail) || empty(getTanggal)) {
            JOptionPane.showMessageDialog(null, "Data yang Anda masukkan belum lengkap!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        } else if (getIdAnggota.length() >=6 || getIdAnggota.length() <= 4) {
            JOptionPane.showMessageDialog(null, "Panjang ID Anggota harus 5 karakter!", "Peringatan!", JOptionPane.WARNING_MESSAGE);
        } else if (!getEmail.matches(".*@student.uinsby.ac.id") && !getEmail.matches(".*@gmail.com")) {
            JOptionPane.showMessageDialog(null, "Email yang anda masukkan salah!", "Peringatan!", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                Connection con = new perpustakaan.koneksi().GetConnection();
                String get = "SELECT * FROM anggota WHERE id_anggota = '"+getIdAnggota+"' OR nama = '"+getNama+"'";
                java.sql.Statement st = con.createStatement();
                java.sql.ResultSet hasil = st.executeQuery(get);
                
                if (hasil.next()) {
                    JOptionPane.showMessageDialog(null, "Data seperti ini sudah pernah Anda masukkan sebelumnya.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
                } else {
                    if(rdLaki.isSelected()){
                        jenkel="L";
                    }else if (rdPerempuan.isSelected()){
                        jenkel="P";
                    }
                    try{
                        String sql = "INSERT INTO anggota VALUES (?, ?, ?, ?, ?);";
                        java.sql.PreparedStatement stat = (PreparedStatement)con.prepareStatement(sql);
                        stat.setString(1, getIdAnggota);
                        stat.setString(2, getNama);
                        stat.setString(3, jenkel);
                        stat.setString(4, getEmail);
                        stat.setString(5, getTanggal);
                        stat.executeUpdate();

                        this.setVisible(false);
                        JOptionPane.showMessageDialog(null, "Data BERHASIL Ditambahkan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "GAGAL Menambahkan Data", "Kesalahan", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jLsimpan2MouseClicked

    private void jLcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLcloseMouseClicked
        // TODO add your handling code here:
        
        dispose();
    }//GEN-LAST:event_jLcloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambahAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambahAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambahAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambahAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tambahAnggota().setVisible(true);
            }
        });
    }
    
    private void random(){
        try {
            Connection con = new perpustakaan.koneksi().GetConnection();
            java.sql.Statement stat = con.createStatement();
            String sql = "SELECT MAX(id_anggota) AS id FROM anggota";
            ResultSet res = stat.executeQuery(sql);
            while(res.next()){
                Object[] obj = new Object[1];
                obj[0]= res.getString("id");
                if(obj[0]== null){
                    obj[0] = "A0000";
                }
                String str_kd = (String) obj[0];
                String kd = str_kd.substring(1,5);
                int code = Integer.parseInt(kd);
                code++;
                String a = String.format("%04d", code);
                String b = "A" + a;
                jTidAnggota.setText(b);
                jTidAnggota.setEditable(false);
            }
        } catch (Exception e) {
        }
    }
    
    private void thisdate() {
        java.util.Date sekarang = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("yyyy-MM-dd") ;
        jTtanggalTerdaftar.setText(""+kal.format(sekarang));
    }
    
    private static boolean empty(final String s) {
        return s == null || s.trim().isEmpty();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupJK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLclose;
    private javax.swing.JLabel jLsimpan2;
    private javax.swing.JTextField jTemail;
    private javax.swing.JTextField jTidAnggota;
    private javax.swing.JTextField jTnamaLengkap;
    private javax.swing.JTextField jTtanggalTerdaftar;
    private javax.swing.JRadioButton rdLaki;
    private javax.swing.JRadioButton rdPerempuan;
    // End of variables declaration//GEN-END:variables
}
