/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class tambahBuku extends javax.swing.JFrame {

    /**
     * Creates new form tambahBuku
     */
    

    public tambahBuku() {
        initComponents();
        random();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLsimpan = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTpenulis = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTkodeBuku = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCBkategori = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTjudulBuku = new javax.swing.JTextField();
        jLclose = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(622, 456));
        setMinimumSize(new java.awt.Dimension(622, 456));
        setPreferredSize(new java.awt.Dimension(622, 456));
        getContentPane().setLayout(null);

        jLsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logo simpan_tambah.png"))); // NOI18N
        jLsimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLsimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLsimpanMouseClicked(evt);
            }
        });
        getContentPane().add(jLsimpan);
        jLsimpan.setBounds(380, 310, 170, 50);

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(136, 96, 84));
        jLabel2.setText("Kategori");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 220, 160, 24);
        getContentPane().add(jTpenulis);
        jTpenulis.setBounds(320, 250, 220, 30);

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(136, 96, 84));
        jLabel3.setText("Judul Buku");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(320, 120, 160, 24);

        jTkodeBuku.setBackground(new java.awt.Color(195, 158, 116));
        getContentPane().add(jTkodeBuku);
        jTkodeBuku.setBounds(50, 150, 220, 30);

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(136, 96, 84));
        jLabel4.setText("Penulis");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 220, 160, 24);

        jCBkategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "umum", "bahasa", "filsafat", "sains", "teknologi" }));
        getContentPane().add(jCBkategori);
        jCBkategori.setBounds(50, 250, 220, 30);

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(136, 96, 84));
        jLabel5.setText("Kode Buku");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 120, 160, 24);
        getContentPane().add(jTjudulBuku);
        jTjudulBuku.setBounds(320, 150, 220, 30);

        jLclose.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLclose.setForeground(new java.awt.Color(255, 0, 51));
        jLclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/x.png"))); // NOI18N
        jLclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLcloseMouseClicked(evt);
            }
        });
        getContentPane().add(jLclose);
        jLclose.setBounds(550, 10, 40, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/halTambahBuku.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLsimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLsimpanMouseClicked
        // TODO add your handling code here:
        String getKode, getJudul, getPenulis, getKategori;

        getKode = jTkodeBuku.getText();
        getJudul = jTjudulBuku.getText();
        getPenulis = jTpenulis.getText();
        getKategori = (String) jCBkategori.getSelectedItem();
//        String AN = "" + (Integer.parseInt(getKode)+1);
//        String nol = "";
//        
//        String kode = (String) jCBkategori.getSelectedItem();
//        if(kode=="umum" && AN.length()==1){
//            nol = "00";
//            jTkodeBuku.setText("A"+nol+AN);
//        }else if (kode=="bahasa" && AN.length()==1){
//            nol = "00";
//            jTkodeBuku.setText("B"+nol+AN);
//        }else if (kode=="filsafat" && AN.length()==1){
//            nol = "00";
//            jTkodeBuku.setText("C"+nol+AN);
//        }else if (kode=="sains" && AN.length()==1){
//            nol = "00";
//            jTkodeBuku.setText("D"+nol+AN);
//        }else if (kode=="teknologi" && AN.length()==1){
//            nol = "00";
//            jTkodeBuku.setText("E"+nol+AN);
//        }

        if (empty(getKode) || empty(getJudul)) {
            JOptionPane.showMessageDialog(null, "Data yang Anda masukkan belum lengkap!", "Peringatan!", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                Connection con = new perpustakaan.koneksi().GetConnection();
                String get = "SELECT * FROM buku WHERE judul_buku = '" + getJudul + "'";
                java.sql.Statement st = con.createStatement();
                java.sql.ResultSet hasil = st.executeQuery(get);

                if (hasil.next()) {
                    JOptionPane.showMessageDialog(null, "Judul buku tidak boleh ada yang sama.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
                } else {
                    try {
                        String sql = "INSERT INTO buku VALUES (?, ?, ?, ?)";
                        java.sql.PreparedStatement stat = (PreparedStatement) con.prepareStatement(sql);
                        stat.setString(1, getKode);
                        stat.setString(2, getJudul);
                        stat.setString(3, getKategori + "");
                        stat.setString(4, getPenulis);
                        stat.executeUpdate();

                        this.setVisible(false);
                        JOptionPane.showMessageDialog(null, "Data BERHASIL Ditambahkan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                    } catch (Exception e) {
                        System.err.println("Terjadi kesalahan:" + e);
                    }
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jLsimpanMouseClicked

    private void jLcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLcloseMouseClicked
        // TODO add your handling code here:

        dispose();
    }//GEN-LAST:event_jLcloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambahBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambahBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambahBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambahBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tambahBuku().setVisible(true);
            }
        });
    }
    
    private void random(){
        try {
            Connection con = new perpustakaan.koneksi().GetConnection();
            java.sql.Statement stat = con.createStatement();
            String sql = "SELECT MAX(kode_buku) AS kode FROM buku";
            ResultSet res = stat.executeQuery(sql);
            while(res.next()){
                Object[] obj = new Object[1];
                obj[0]= res.getString("kode");
                if(obj[0]== null){
                    obj[0] = "B0000";
                }
                String str_kd = (String) obj[0];
                String kd = str_kd.substring(1,5);
                int code = Integer.parseInt(kd);
                code++;
                String a = String.format("%04d", code);
                String b = "B" + a;
                jTkodeBuku.setText(b);
                jTkodeBuku.setEditable(false);
            }
        } catch (Exception e) {
        }
    }

    private static boolean empty(final String s) {
        return s == null || s.trim().isEmpty();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCBkategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLclose;
    private javax.swing.JLabel jLsimpan;
    private javax.swing.JTextField jTjudulBuku;
    private javax.swing.JTextField jTkodeBuku;
    private javax.swing.JTextField jTpenulis;
    // End of variables declaration//GEN-END:variables
}
