/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class ubahPeminjaman extends javax.swing.JFrame {

    /**
     * Creates new form ubahPeminjaman
     */
    
    DefaultTableModel tbl1 = new DefaultTableModel() {
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    
    DefaultTableModel tbl2 = new DefaultTableModel() {
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    
    public ubahPeminjaman() {
        initComponents();
        tampil_buku();
        tampil_anggota();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTcariBuku = new javax.swing.JTextField();
        jTcariAnggota = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTidAnggota = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTnama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTemail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTkodeBuku = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTjudulBuku = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCBkategori = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTtanggalPinjam = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAnggota = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableBuku = new javax.swing.JTable();
        jLsimpan3 = new javax.swing.JLabel();
        jLclose = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        id_peminjaman = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(876, 767));
        setMinimumSize(new java.awt.Dimension(876, 767));
        setPreferredSize(new java.awt.Dimension(890, 780));
        getContentPane().setLayout(null);

        jTcariBuku.setToolTipText("Cari Anggota");
        jTcariBuku.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTcariBukuKeyTyped(evt);
            }
        });
        getContentPane().add(jTcariBuku);
        jTcariBuku.setBounds(20, 160, 360, 30);

        jTcariAnggota.setToolTipText("Cari Buku");
        jTcariAnggota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTcariAnggotaKeyTyped(evt);
            }
        });
        getContentPane().add(jTcariAnggota);
        jTcariAnggota.setBounds(20, 120, 360, 30);

        jLabel6.setFont(new java.awt.Font("Britannic Bold", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(136, 96, 84));
        jLabel6.setText("Data Anggota");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(120, 210, 150, 18);

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(136, 96, 84));
        jLabel7.setText("ID Anggota");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 240, 150, 24);
        getContentPane().add(jTidAnggota);
        jTidAnggota.setBounds(20, 270, 360, 26);

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(136, 96, 84));
        jLabel5.setText("Nama");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 300, 150, 22);
        getContentPane().add(jTnama);
        jTnama.setBounds(20, 330, 360, 26);

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(136, 96, 84));
        jLabel2.setText("Email");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 360, 150, 24);
        getContentPane().add(jTemail);
        jTemail.setBounds(20, 390, 360, 26);

        jLabel3.setFont(new java.awt.Font("Britannic Bold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(136, 96, 84));
        jLabel3.setText("Data Buku");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 430, 110, 24);

        jLabel10.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(136, 96, 84));
        jLabel10.setText("Kode Buku");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 460, 150, 24);
        getContentPane().add(jTkodeBuku);
        jTkodeBuku.setBounds(20, 490, 360, 26);

        jLabel9.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(136, 96, 84));
        jLabel9.setText("Judul Buku");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 520, 150, 24);
        getContentPane().add(jTjudulBuku);
        jTjudulBuku.setBounds(20, 550, 360, 26);

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(136, 96, 84));
        jLabel4.setText("Kategori");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 580, 150, 24);

        jCBkategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "umum", "bahasa", "filsafat", "sains", "teknologi" }));
        getContentPane().add(jCBkategori);
        jCBkategori.setBounds(20, 610, 360, 26);

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(136, 96, 84));
        jLabel8.setText("Tanggal Peminjaman (YYYY-MM-DD)");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 650, 350, 24);
        getContentPane().add(jTtanggalPinjam);
        jTtanggalPinjam.setBounds(20, 680, 360, 26);

        jTableAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableAnggota.setSelectionBackground(new java.awt.Color(208, 180, 142));
        jTableAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAnggotaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAnggota);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(400, 120, 452, 290);

        jTableBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableBuku.setSelectionBackground(new java.awt.Color(208, 180, 142));
        jTableBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBukuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableBuku);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(400, 430, 452, 230);

        jLsimpan3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logo simpan_ubah.png"))); // NOI18N
        jLsimpan3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLsimpan3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLsimpan3MouseClicked(evt);
            }
        });
        getContentPane().add(jLsimpan3);
        jLsimpan3.setBounds(690, 670, 170, 40);

        jLclose.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLclose.setForeground(new java.awt.Color(255, 0, 51));
        jLclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/x.png"))); // NOI18N
        jLclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLcloseMouseClicked(evt);
            }
        });
        getContentPane().add(jLclose);
        jLclose.setBounds(810, 10, 40, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/hal ubah peminjaman.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 870, 730);

        id_peminjaman.setText("jLabel11");
        getContentPane().add(id_peminjaman);
        id_peminjaman.setBounds(790, 80, 60, 20);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTcariAnggotaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTcariAnggotaKeyTyped
        // TODO add your handling code here:
        search_anggota();
    }//GEN-LAST:event_jTcariAnggotaKeyTyped

    private void jTcariBukuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTcariBukuKeyTyped
        // TODO add your handling code here:
        search_book();
    }//GEN-LAST:event_jTcariBukuKeyTyped

    private void jTableAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAnggotaMouseClicked
        // TODO add your handling code here:
        clicktbl_anggota();
    }//GEN-LAST:event_jTableAnggotaMouseClicked

    private void jTableBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBukuMouseClicked
        // TODO add your handling code here:
        clicktbl_buku();
    }//GEN-LAST:event_jTableBukuMouseClicked

    private void jLsimpan3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLsimpan3MouseClicked
        // TODO add your handling code here:
        save();
    }//GEN-LAST:event_jLsimpan3MouseClicked

    private void jLcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLcloseMouseClicked
        // TODO add your handling code here:
        
        dispose();
    }//GEN-LAST:event_jLcloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ubahPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ubahPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ubahPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ubahPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ubahPeminjaman().setVisible(true);
            }
        });
    }
    
    private void tampil_buku(){
        Object []baris = {"Kode Buku", "Judul Buku", "Kategori"};
        tbl1 = new DefaultTableModel(null, baris) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTableBuku.setModel(tbl1);
        
        try{
            Connection con = new perpustakaan.koneksi().GetConnection();
            String sql = "SELECT * FROM buku ORDER BY kode_buku ASC";
            java.sql.Statement st = con.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);
            
            while (rs.next()) {
                String kode = rs.getString("kode_buku");
                String judul = rs.getString("judul_buku");
                String kategori = rs.getString("kategori");
                
                String[] data = {kode, judul, kategori};
                tbl1.addRow(data);
            }
            
        }catch(Exception e){
            System.err.println("Terjadi kesalahan:"+e);
        }
    }
    
    private void tampil_anggota(){
        Object []baris = {"ID Anggota", "Nama", "Email"};
        tbl2 = new DefaultTableModel(null, baris) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTableAnggota.setModel(tbl2);
        
        try{
            Connection con = new perpustakaan.koneksi().GetConnection();
            String sql = "SELECT * FROM anggota ORDER BY id_anggota ASC";
            java.sql.Statement st = con.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);
            
            while (rs.next()) {
                String idAnggota = rs.getString("ID_Anggota");
                String nama = rs.getString("Nama");
                String email = rs.getString("Email");
                
                String[] data = {idAnggota, nama, email};
                tbl2.addRow(data);
            }
            
        }catch(Exception e){
           System.err.println("Terjadi kesalahan:"+e);
        }
    }
    
    private void search_book() {
        String query = jTcariBuku.getText();
        Object []baris = {"Kode Buku", "Judul Buku", "Kategori"};
        tbl1 = new DefaultTableModel(null, baris) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTableBuku.setModel(tbl1);
        
        try{
            Connection con = new perpustakaan.koneksi().GetConnection();
            String sql = "SELECT * FROM buku WHERE BINARY "
                    + "kode_buku LIKE '%"+query+"%' "
                    + "OR judul_buku LIKE '%"+query+"%' "
                    + "OR kategori LIKE '%"+query+"%' "
                    + "OR penulis LIKE '%"+query+"%' "
                    + "ORDER BY kode_buku ASC";
            java.sql.Statement stmt = con.createStatement();
            java.sql.ResultSet hasil = stmt.executeQuery(sql);
            
            while (hasil.next()) {
                String kode = hasil.getString("kode_buku");
                String judul = hasil.getString("judul_buku");
                String kategori = hasil.getString("kategori");
                
                String[] data = {kode, judul, kategori};
                tbl1.addRow(data);
            }
        }catch(Exception e){
            
        }
    }
    
    private void search_anggota() {
        String query = jTcariAnggota.getText();
        
        Object []baris = {"ID Anggota", "Nama", "Email"};
        tbl2 = new DefaultTableModel(null, baris) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTableAnggota.setModel(tbl2);
        
        try{
            Connection con = new perpustakaan.koneksi().GetConnection();
            String sql = "SELECT * FROM anggota WHERE BINARY "
                    + "id_anggota LIKE '%"+query+"%' "
                    + "OR nama LIKE '%"+query+"%' "
                    + "OR jenis_kelamin LIKE '%"+query+"%' "
                    + "OR email LIKE '%"+query+"%' "
                    + "ORDER BY id_anggota ASC";
            java.sql.Statement stmt = con.createStatement();
            java.sql.ResultSet hasil = stmt.executeQuery(sql);
            
            while (hasil.next()) {
                String idAnggota = hasil.getString("id_anggota");
                String nama = hasil.getString("nama");
                String email = hasil.getString("email");
                
                String[] data = {idAnggota, nama, email};
                tbl2.addRow(data);
            }
        }catch(Exception e){
            
        }
    }
    
    private void clicktbl_anggota() {
        int baris = jTableAnggota.getSelectedRow();
        
        jTidAnggota.setText((String)tbl2.getValueAt(baris, 0));
        jTnama.setText((String)tbl2.getValueAt(baris, 1));
        jTemail.setText((String)tbl2.getValueAt(baris, 2));
    }
    
    private void clicktbl_buku(){
        int baris = jTableBuku.getSelectedRow();
        
        jTkodeBuku.setText((String)tbl1.getValueAt(baris, 0));
        jTjudulBuku.setText((String)tbl1.getValueAt(baris, 1));
        jCBkategori.setSelectedItem((String)tbl1.getValueAt(baris, 2));
        
        try{
            Connection con = new perpustakaan.koneksi().GetConnection();
            String sql = "SELECT * FROM buku WHERE kode_buku = '"+(String)tbl1.getValueAt(baris, 0)+"'";
            java.sql.Statement stat = con.createStatement();
            java.sql.ResultSet rs = stat.executeQuery(sql);
            if (rs.next()) {
                jCBkategori.setSelectedItem(rs.getString("kategori"));
            }
        }catch (Exception e){
            
        }            
    }
    
    private void save(){
        String id = null, getIdAnggota, getNama, getEmail, getKodeBuku, getJudulBuku, getKategori, getTanggal;
        
        getIdAnggota = jTidAnggota.getText();
        getNama = jTnama.getText();
        getEmail = jTemail.getText();
        getKodeBuku = jTkodeBuku.getText();
        getJudulBuku = jTjudulBuku.getText();
        getKategori = (String) jCBkategori.getSelectedItem();
        getTanggal = jTtanggalPinjam.getText();
        
//        id= id_peminjaman.getText();
        if (empty(getIdAnggota) || empty(getKodeBuku) || empty(getTanggal)) {
            JOptionPane.showMessageDialog(null, "Data yang Anda masukkan belum lengkap!", "Peringatan!", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
            Connection con = new perpustakaan.koneksi().GetConnection();
            String sql = "UPDATE peminjaman SET id_anggota=?, nama=?, email=?, kode_buku=?, judul_buku=?, "
                    + "tanggal_pinjam=? WHERE id = '"+id+"'";
            java.sql.PreparedStatement stat = (PreparedStatement)con.prepareStatement(sql);
            stat.setString(1, getIdAnggota);
            stat.setString(2, getNama);
            stat.setString(3, getEmail);
            stat.setString(4, getKodeBuku);
            stat.setString(5, getJudulBuku);
            stat.setString(6, getTanggal);
            stat.executeUpdate();
            
            this.setVisible(false);
            
            JOptionPane.showMessageDialog(null, "Data BERHASIL Diubah", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                 System.err.println("Terjadi kesalahan:"+e);
            }
        }
    }
    
     private static boolean empty(final String s) {
        return s == null || s.trim().isEmpty();
    }
     
    public void tampilDataPeminjaman(String Id){
        try {
            Connection con = new perpustakaan.koneksi().GetConnection();
            String sql = "select*from peminjaman where id like '%"+Id+"%'";
            java.sql.Statement st = con.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                jTidAnggota.setText(rs.getString("id_anggota"));
                jTnama.setText(rs.getString("nama"));
                jTemail.setText(rs.getString("email"));
                jTkodeBuku.setText(rs.getString("kode_buku"));
                jTjudulBuku.setText(rs.getString("judul_buku"));
                jTtanggalPinjam.setText(rs.getString("tanggal_pinjam"));
            }
            
        } catch (Exception e) {
            System.err.println("Terjadi kesalahan:"+e);
        }
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel id_peminjaman;
    private javax.swing.JComboBox<String> jCBkategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLclose;
    private javax.swing.JLabel jLsimpan3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAnggota;
    private javax.swing.JTable jTableBuku;
    private javax.swing.JTextField jTcariAnggota;
    private javax.swing.JTextField jTcariBuku;
    private javax.swing.JTextField jTemail;
    private javax.swing.JTextField jTidAnggota;
    private javax.swing.JTextField jTjudulBuku;
    private javax.swing.JTextField jTkodeBuku;
    private javax.swing.JTextField jTnama;
    private javax.swing.JTextField jTtanggalPinjam;
    // End of variables declaration//GEN-END:variables
}
