/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;

import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class ubahAnggota extends javax.swing.JFrame {


    /**
     * Creates new form ubahAnggota
     */
    public ubahAnggota() {
        initComponents();
        jTidAnggota.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupJK = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        jTidAnggota = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTemail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTnamaLengkap = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rdPerempuan = new javax.swing.JRadioButton();
        rdLaki = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jTtanggalTerdaftar = new javax.swing.JTextField();
        jLsimpan2 = new javax.swing.JLabel();
        jLclose = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(622, 456));
        getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(136, 96, 84));
        jLabel6.setText("ID Anggota");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 110, 160, 24);

        jTidAnggota.setBackground(new java.awt.Color(195, 158, 116));
        getContentPane().add(jTidAnggota);
        jTidAnggota.setBounds(50, 140, 220, 30);

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(136, 96, 84));
        jLabel7.setText("Email");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(330, 110, 160, 24);
        getContentPane().add(jTemail);
        jTemail.setBounds(330, 140, 220, 30);

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(136, 96, 84));
        jLabel2.setText("Nama Lengkap");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 190, 190, 24);
        getContentPane().add(jTnamaLengkap);
        jTnamaLengkap.setBounds(50, 220, 220, 30);

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(136, 96, 84));
        jLabel3.setText("Jenis Kelamin");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(330, 190, 190, 29);

        buttonGroupJK.add(rdPerempuan);
        rdPerempuan.setFont(new java.awt.Font("Leelawadee UI", 1, 20)); // NOI18N
        rdPerempuan.setForeground(new java.awt.Color(136, 96, 84));
        rdPerempuan.setText("P");
        getContentPane().add(rdPerempuan);
        rdPerempuan.setBounds(330, 220, 50, 35);

        buttonGroupJK.add(rdLaki);
        rdLaki.setFont(new java.awt.Font("Leelawadee UI", 1, 20)); // NOI18N
        rdLaki.setForeground(new java.awt.Color(136, 96, 84));
        rdLaki.setText("L");
        rdLaki.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(rdLaki);
        rdLaki.setBounds(420, 220, 50, 35);

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(136, 96, 84));
        jLabel5.setText("Tanggal Terdaftar (YYYY-MM-DD)");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 270, 420, 24);
        getContentPane().add(jTtanggalTerdaftar);
        jTtanggalTerdaftar.setBounds(50, 300, 220, 30);

        jLsimpan2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logo simpan_ubah.png"))); // NOI18N
        jLsimpan2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLsimpan2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLsimpan2MouseClicked(evt);
            }
        });
        getContentPane().add(jLsimpan2);
        jLsimpan2.setBounds(390, 320, 170, 50);

        jLclose.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLclose.setForeground(new java.awt.Color(255, 0, 51));
        jLclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/x.png"))); // NOI18N
        jLclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLcloseMouseClicked(evt);
            }
        });
        getContentPane().add(jLclose);
        jLclose.setBounds(550, 10, 40, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/halUbahAnggota.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLsimpan2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLsimpan2MouseClicked
        // TODO add your handling code here:
        String getIdAnggota, getNama, getEmail, jenkel, getTanggal;
        getIdAnggota = jTidAnggota.getText();
        getNama = jTnamaLengkap.getText();
        getEmail = jTemail.getText();
        getTanggal = jTtanggalTerdaftar.getText();
        StringBuffer jk = new StringBuffer();
        if(rdPerempuan.isSelected()){
            jk.append(rdPerempuan.getText());
        }else if(rdLaki.isSelected()){
            jk.append(rdLaki.getText());
        }
        jenkel = jk.toString();
        
        if (empty(getIdAnggota) || empty(getNama) || empty(getEmail) || empty(getTanggal)) {
            JOptionPane.showMessageDialog(null, "Data yang Anda masukkan belum lengkap!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        } else if (getIdAnggota.length() >=6 || getIdAnggota.length() <= 4){
            JOptionPane.showMessageDialog(null, "Panjang ID Anggota harus 5 karakter!", "Peringatan!", JOptionPane.WARNING_MESSAGE);
        } else{
            try {
                Connection con = new perpustakaan.koneksi().GetConnection();
                String sql = "UPDATE anggota SET id_anggota=?, nama=?, jenis_kelamin=?, "
                        + "email=?, tanggal_terdaftar=? WHERE id_anggota = '"+getIdAnggota+"'";
                java.sql.PreparedStatement stat = con.prepareStatement(sql);
                stat.setString(1, getIdAnggota);
                stat.setString(2, getNama);
                stat.setString(3, jenkel);
                stat.setString(4, getEmail);
                stat.setString(5, getTanggal);
                stat.executeUpdate();
                
                this.setVisible(false);
                
                JOptionPane.showMessageDialog(null, "Data BERHASIL Diubah", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "GAGAL Mengubah Data", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jLsimpan2MouseClicked

    private void jLcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLcloseMouseClicked
        // TODO add your handling code here:
        
        dispose();
    }//GEN-LAST:event_jLcloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ubahAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ubahAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ubahAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ubahAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ubahAnggota().setVisible(true);
            }
        });
    }
    
    public void tampilDataAnggota(String IdAnggota){
        try {
            Connection con = new perpustakaan.koneksi().GetConnection();
            String sql = "select*from anggota where id_anggota like '%"+IdAnggota+"%'";
            java.sql.Statement st = con.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                jTidAnggota.setText(rs.getString("id_anggota"));
                jTnamaLengkap.setText(rs.getString("nama"));
                if("P".equals(rs.getString("jenis_kelamin"))){
                    rdPerempuan.setSelected(true);
                }else{
                    rdLaki.setSelected(true);
                }
                jTemail.setText(rs.getString("email"));
                jTtanggalTerdaftar.setText(rs.getString("tanggal_terdaftar"));
            }
        } catch (Exception e) {
            System.err.println("Terjadi kesalahan:"+e);
        }
        
    }
    
    private static boolean empty(final String s) {
        return s == null || s.trim().isEmpty();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupJK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLclose;
    private javax.swing.JLabel jLsimpan2;
    private javax.swing.JTextField jTemail;
    private javax.swing.JTextField jTidAnggota;
    private javax.swing.JTextField jTnamaLengkap;
    private javax.swing.JTextField jTtanggalTerdaftar;
    private javax.swing.JRadioButton rdLaki;
    private javax.swing.JRadioButton rdPerempuan;
    // End of variables declaration//GEN-END:variables
}
